files:
  "/etc/pki/tls/certs/cloudflare-origin.crt":
    mode: "000644"
    owner: root
    group: root
    content: |
      CERT_PLACEHOLDER

  "/etc/pki/tls/private/cloudflare-origin.key":
    mode: "000600"
    owner: root
    group: root
    content: |
      KEY_PLACEHOLDER